import type { Metadata } from "next";
import { AppChakraProvider } from "@/src/app/providers/CackraProvider";
import "./globals.css";

export const metadata: Metadata = {
    title: "FoxTask",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
                <AppChakraProvider>
                    {children}
                </AppChakraProvider>
            </body>
        </html>
    );
}
